Feature | Skill lookup
hoXyy/discord-megaten-fusion-bot pull request #8
Opened 2023-02-08 21:21 UTC by povka

2023-02-08 23:52 UTC, hoXyy requested changes

2023-02-08 23:52 UTC, hoXyy commented on src/commands/requestSkill.ts
> +        .setDescription("The game to get the skil from.")
Small typo in the description

2023-02-09 09:41 UTC, povka commented on src/commands/requestSkill.ts
> +        .setDescription("The game to get the skil from.")
Done @hoXyy

2023-02-09 19:52 UTC, hoXyy approved these changes

2023-02-09 20:13 UTC, merged